"""
Synchronous Motor Physics Model.
Calculates V-curves, inverted V-curves (PF vs If), synchronous condenser operation,
torque angle delta, pull-out torque, and stability limits.
"""

import numpy as np
from typing import Dict, Any
from .base import MachinePhysicsModel, angular_velocity, synchronous_speed

class SynchronousMotorPhysics(MachinePhysicsModel):
    def __init__(self):
        super().__init__("3-Phase Synchronous Motor")

    def get_validity_range(self) -> Dict[str, Any]:
        return {
            "v_line": (200.0, 6600.0),
            "frequency": (25.0, 60.0),
            "poles": [2, 4, 6, 8],
            "load_power_w": (0.0, 50000.0),
            "field_current_a": (0.1, 10.0)
        }

    def calculate(self, inputs: Dict[str, Any], params: Dict[str, Any]) -> Dict[str, Any]:
        v_line = float(inputs.get("v_line", 415.0))
        frequency = float(inputs.get("frequency", 50.0))
        load_power = float(inputs.get("load_power_w", 3500.0))  # Shaft mechanical load in Watts
        if_current = float(inputs.get("field_current_a", 1.5))   # DC excitation in Amps

        poles = int(params.get("poles", 4))
        ra = float(params.get("ra", 0.5))
        xs = float(params.get("xs", 5.0))
        p_rot = float(params.get("p_rot", 200.0))

        # Speed is strictly synchronous at steady-state: N = 120 * f / P
        ns_rpm = synchronous_speed(frequency, poles)
        omega_s = angular_velocity(ns_rpm)

        v_ph = v_line / np.sqrt(3.0)

        # Back EMF Ef generated by rotor excitation:
        # Base excitation constant:
        ef_ph = (v_ph * 0.95) * (if_current / 1.5)

        # Total electromechanical power converted:
        p_conv = load_power + p_rot

        # Power-angle relation: P_conv = (3 * V_ph * Ef / Xs) * sin(delta)
        # Therefore: sin(delta) = (P_conv * Xs) / (3 * V_ph * Ef)
        max_power = (3.0 * v_ph * ef_ph) / xs if xs > 0 else 1.0
        ratio = p_conv / max_power if max_power > 0 else 0.0

        is_stable = ratio <= 1.0
        delta_rad = np.arcsin(min(1.0, max(-1.0, ratio))) if is_stable else np.pi / 2.0
        delta_deg = float(np.degrees(delta_rad))

        # Phasor equation: V_ph /_ 0 = Ef /_ -delta + Ia * (Ra + jXs)
        # Ia = (V_ph - Ef*(cos(delta) - j*sin(delta))) / (Ra + j*Xs)
        ef_complex = ef_ph * (np.cos(delta_rad) - 1j * np.sin(delta_rad))
        zs = complex(ra, xs)
        ia_complex = (v_ph - ef_complex) / zs

        ia_mag = float(abs(ia_complex))
        # Power factor angle
        phi_rad = float(np.angle(ia_complex))
        pf = float(np.cos(phi_rad))
        pf_mode = "Lagging" if np.sin(phi_rad) < 0 else "Leading" if np.sin(phi_rad) > 0 else "Unity"

        p_in = float(3.0 * v_ph * ia_mag * pf)
        t_shaft = float(load_power / omega_s) if omega_s > 0 else 0.0
        efficiency = float((load_power / p_in * 100.0) if p_in > 0 else 0.0)

        return {
            "speed_rpm": float(ns_rpm),
            "synchronous_speed_rpm": float(ns_rpm),
            "armature_current_a": float(ia_mag),
            "field_current_a": float(if_current),
            "power_factor": float(pf),
            "power_factor_mode": pf_mode,
            "torque_angle_delta_deg": float(delta_deg),
            "pull_out_torque_nm": float((max_power / omega_s) if omega_s > 0 else 0.0),
            "shaft_torque_nm": float(t_shaft),
            "input_power_w": float(p_in),
            "output_power_w": float(load_power),
            "efficiency_pct": float(min(100.0, max(0.0, efficiency))),
            "is_pull_out_exceeded": not is_stable
        }
